#!/bin/bash
#
# (Re)Generate version.h with the version given on the command line
# Avoid regenerating if the version has not changed.
#

VERSION="$1"

cat > version.h.tmp <<-EOF
	!!!!! GENERATED BY version_h_gen.sh SCRIPT; DO NOT EDIT !!!!!
	CHARACTER(len=100) :: VERSION = &
	  & "$VERSION"
EOF

cmp -s version.h.tmp version.h && rm -f version.h.tmp || mv version.h.tmp version.h
