#!/bin/bash
#
# (Re)Generate version.h with the version given on the command line
# Avoid regenerating if the version has not changed.
#

VERSION="$1"

cat <<-EOF
	!!!!! GENERATED BY $(basename $0); DO NOT EDIT !!!!!
	CHARACTER(len=100) :: VERSION = &
	  & "$VERSION"
EOF
